services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hms-api
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@hms-db:5432/${POSTGRES_DB:-hms}
    depends_on:
      - hms-db
      - hms-redis
    volumes:
      - ./.env:/app/.env
      - ./node_modules:/app/node_modules
      - ./media:/app/media
    networks:
      - app-network

  hms-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-hms}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
  
  hms-redis: 
    image: redis:latest
    container_name: hms-redis
    ports:
      - '6379:6379'
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge 